<wsdl:definitions name="ProductDetails" targetNamespace="http://xmlns.oracle.com/MozaApplication/GetAllProducts_TD/ProductDetails" xmlns:tns="http://xmlns.oracle.com/MozaApplication/GetAllProducts_TD/ProductDetails" xmlns:inp1="http://www.mozabank.org/MSB/TDProducts" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="ProductDetails">
        <plnk:role name="ProductDetailsProvider" portType="tns:ProductDetails_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.mozabank.org/MSB/TDProducts" schemaLocation="../Schema/GetProductTD_MSB.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ProductDetails_inputMessage">
        <wsdl:part name="request" element="inp1:Request"/>
    </wsdl:message>
    <wsdl:message name="ProductDetails_outputMessage">
        <wsdl:part name="reply" element="inp1:Response"/>
    </wsdl:message>
    <wsdl:portType name="ProductDetails_ptt">
        <wsdl:operation name="ProductDetails">
            <wsdl:input message="tns:ProductDetails_inputMessage"/>
            <wsdl:output message="tns:ProductDetails_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ProductDetails_ptt-binding" type="tns:ProductDetails_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ProductDetails">
            <soap:operation soapAction="ProductDetails"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>