<wsdl:definitions name="CTFO-MSB" targetNamespace="http://xmlns.oracle.com/ServiceBusApplication/GetAllOtherBankTransfer/CTFO-MSB" xmlns:tns="http://xmlns.oracle.com/ServiceBusApplication/GetAllOtherBankTransfer/CTFO-MSB" xmlns:inp1="http://www.mozabanca.org/obdx/CTFO" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="CTFO-MSB">
        <plnk:role name="CTFO-MSBProvider" portType="tns:CTFO-MSB_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.mozabanca.org/obdx/CTFO" schemaLocation="../CTFO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="CTFOGET_inputMessage">
        <wsdl:part name="request" element="inp1:RequestEncoded"/>
    </wsdl:message>
    <wsdl:message name="CTFOGET_outputMessage">
        <wsdl:part name="reply" element="inp1:Response"/>
    </wsdl:message>
    <wsdl:portType name="CTFO-MSB_ptt">
        <wsdl:operation name="CTFOGET">
            <wsdl:input message="tns:CTFOGET_inputMessage"/>
            <wsdl:output message="tns:CTFOGET_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CTFO-MSB_ptt-binding" type="tns:CTFO-MSB_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="CTFOGET">
            <soap:operation soapAction="CTFOGET"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>