<wsdl:definitions name="ExchangeRatesCache" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT14/SessionParams/ExchangeRatesCache" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT14/SessionParams/ExchangeRatesCache" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ExchangeRatesCache" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ExchangeRatesCache_plt">
    <plt:role name="ExchangeRatesCache_role">
      <plt:portType name="tns:ExchangeRatesCache_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ExchangeRatesCache" schemaLocation="ExchangeRatesCache_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="XchgRateCachedResultCollection_msg">
        <wsdl:part name="XchgRateCachedResultCollection" element="top:XchgRateCachedResultCollection"/>
    </wsdl:message>
    <wsdl:portType name="ExchangeRatesCache_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:XchgRateCachedResultCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>