<wsdl:definitions name="InsertBranchListBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT23/SessionParams/InsertBranchListBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT23/SessionParams/InsertBranchListBS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertBranchListBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="InsertBranchListBS_plt">
    <plt:role name="InsertBranchListBS_role">
      <plt:portType name="tns:InsertBranchListBS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertBranchListBS" schemaLocation="InsertBranchListBS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="BranchListCachedResultCollection_msg">
        <wsdl:part name="BranchListCachedResultCollection" element="top:BranchListCachedResultCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertBranchListBS_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:BranchListCachedResultCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>