<wsdl:definitions name="InsertCachePayloadBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SB0608/SessionParams/InsertCachePayloadBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SB0608/SessionParams/InsertCachePayloadBS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertCachePayloadBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="InsertCachePayloadBS_plt">
    <plt:role name="InsertCachePayloadBS_role">
      <plt:portType name="tns:InsertCachePayloadBS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertCachePayloadBS" schemaLocation="InsertCachePayloadBS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="OverviewWidgetCollection_msg">
        <wsdl:part name="OverviewWidgetCollection" element="top:OverviewWidgetCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertCachePayloadBS_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:OverviewWidgetCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>