<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT23/SessionParams/InsertBranchListBS" name="InsertBranchListBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="InsertBranchListBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT23/SessionParams/InsertBranchListBS"/>
    <wsdl:binding name="InsertBranchListBS_ptt-binding" type="ins:InsertBranchListBS_ptt" xmlns:ins="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT23/SessionParams/InsertBranchListBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>