<wsdl:definitions name="QuerySessions" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication31/SessionParams/QuerySessions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication31/SessionParams/QuerySessions" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QuerySessions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QuerySessions_plt">
    <plt:role name="QuerySessions_role">
      <plt:portType name="tns:QuerySessions_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QuerySessions" schemaLocation="QuerySessions_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QuerySessionsSelect_inputParameters">
        <wsdl:part name="QuerySessionsSelect_inputParameters" element="top:QuerySessionsSelect_partyIDInputParameters"/>
    </wsdl:message>
    <wsdl:message name="SessionTxnUserCollection_msg">
        <wsdl:part name="SessionTxnUserCollection" element="top:SessionTxnUserCollection"/>
    </wsdl:message>
    <wsdl:portType name="QuerySessions_ptt">
        <wsdl:operation name="QuerySessionsSelect">
            <wsdl:input message="tns:QuerySessionsSelect_inputParameters"/>
            <wsdl:output message="tns:SessionTxnUserCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>