<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SB0608/SessionParams/QueryCachedResponse" name="QueryCachedResponse-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="QueryCachedResponse.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SB0608/SessionParams/QueryCachedResponse"/>
    <wsdl:binding name="QueryCachedResponse_ptt-binding" type="quer:QueryCachedResponse_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/SB0608/SessionParams/QueryCachedResponse">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>