<wsdl:definitions name="QueryCachedResponse" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SB0608/SessionParams/QueryCachedResponse" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SB0608/SessionParams/QueryCachedResponse" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryCachedResponse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryCachedResponse_plt">
    <plt:role name="QueryCachedResponse_role">
      <plt:portType name="tns:QueryCachedResponse_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryCachedResponse" schemaLocation="QueryCachedResponse_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="OverviewWidgetCollection_msg">
        <wsdl:part name="OverviewWidgetCollection" element="top:OverviewWidgetCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryCachedResponse_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:OverviewWidgetCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>