<wsdl:definitions name="QueryBranchListBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT23/SessionParams/QueryBranchListBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT23/SessionParams/QueryBranchListBS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryBranchListBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryBranchListBS_plt">
    <plt:role name="QueryBranchListBS_role">
      <plt:portType name="tns:QueryBranchListBS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryBranchListBS" schemaLocation="QueryBranchListBS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryBranchListBSSelect_inputParameters">
        <wsdl:part name="QueryBranchListBSSelect_inputParameters" element="top:QueryBranchListBSSelect_branchIdInputParameters"/>
    </wsdl:message>
    <wsdl:message name="BranchListCachedResultCollection_msg">
        <wsdl:part name="BranchListCachedResultCollection" element="top:BranchListCachedResultCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryBranchListBS_ptt">
        <wsdl:operation name="QueryBranchListBSSelect">
            <wsdl:input message="tns:QueryBranchListBSSelect_inputParameters"/>
            <wsdl:output message="tns:BranchListCachedResultCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>