<wsdl:definitions name="QueryExchangeRates" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT14/SessionParams/QueryExchangeRates" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SEPT14/SessionParams/QueryExchangeRates" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryExchangeRates" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryExchangeRates_plt">
    <plt:role name="QueryExchangeRates_role">
      <plt:portType name="tns:QueryExchangeRates_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryExchangeRates" schemaLocation="QueryExchangeRates_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryExchangeRatesSelect_inputParameters">
        <wsdl:part name="QueryExchangeRatesSelect_inputParameters" element="top:QueryExchangeRatesSelect_curr1InputParameters"/>
    </wsdl:message>
    <wsdl:message name="XchgRateCachedResultCollection_msg">
        <wsdl:part name="XchgRateCachedResultCollection" element="top:XchgRateCachedResultCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryExchangeRates_ptt">
        <wsdl:operation name="QueryExchangeRatesSelect">
            <wsdl:input message="tns:QueryExchangeRatesSelect_inputParameters"/>
            <wsdl:output message="tns:XchgRateCachedResultCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>