<wsdl:definitions name="IntlTransService" targetNamespace="http://xmlns.oracle.com/ServiceBusApplication/IntlTransService/IntlTransService" xmlns:tns="http://xmlns.oracle.com/ServiceBusApplication/IntlTransService/IntlTransService" xmlns:inp1="http://www.mozabank.org/internalTransfer" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="IntlTransService">
        <plnk:role name="IntlTransServiceProvider" portType="tns:IntlTransService_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.mozabank.org/internalTransfer" schemaLocation="../INTERNAL_TRANSFER.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="IntlServ_inputMessage">
        <wsdl:part name="request" element="inp1:Request"/>
    </wsdl:message>
    <wsdl:message name="IntlServ_outputMessage">
        <wsdl:part name="reply" element="inp1:Response"/>
    </wsdl:message>
    <wsdl:portType name="IntlTransService_ptt">
        <wsdl:operation name="IntlServ">
            <wsdl:input message="tns:IntlServ_inputMessage"/>
            <wsdl:output message="tns:IntlServ_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="IntlTransService_ptt-binding" type="tns:IntlTransService_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="IntlServ">
            <soap:operation soapAction="IntlServ"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>