<wsdl:definitions name="CGER_BS" targetNamespace="http://xmlns.oracle.com/LOT2/CGERService/CGER_BS" xmlns:tns="http://xmlns.oracle.com/LOT2/CGERService/CGER_BS" xmlns:inp1="http://www.mozabanca.org/CGER" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="CGER_BS">
        <plnk:role name="CGER_BSProvider" portType="tns:CGER_BS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.mozabanca.org/CGER" schemaLocation="../CGER.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="Operation1_inputMessage">
        <wsdl:part name="request" element="inp1:CPCAEncodedRequest"/>
    </wsdl:message>
    <wsdl:message name="Operation1_outputMessage">
        <wsdl:part name="reply" element="inp1:Response"/>
    </wsdl:message>
    <wsdl:portType name="CGER_BS_ptt">
        <wsdl:operation name="Operation1">
            <wsdl:input message="tns:Operation1_inputMessage"/>
            <wsdl:output message="tns:Operation1_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CGER_BS_ptt-binding" type="tns:CGER_BS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Operation1">
            <soap:operation soapAction="Operation1"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>